server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/practice?useSSL=false
    username: root
    password: 122112
    driver-class-name: com.mysql.jdbc.Driver
mybatis:
  type-aliases-package: cn.itcast.user.pojo
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    cn.itcast: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS